-- ============================================================================
-- Diez recetas pasan a ser cursos de El Charcu Pro (2026-10-03)
--
-- ⚠️ GENERADA por `scripts/cursos-desde-recetas.ts`. No se edita a mano: se
-- cambia la receta o el script y se vuelve a generar en una migración nueva.
--
-- Cada receta es un mini curso con la forma del lomo curado: Bienvenida (video),
-- Antes de empezar (texto: ingredientes y proporción), Paso a paso (videos de
-- dos o tres pasos) y Terminar (texto de cocción y consejos, imagen final).
--
--   · Acceso `pago`, estado `publicado`: salen en Cursos maestros como PRO y
--     el contenido solo lo abre quien tiene suscripción (RLS, D12).
--   · ⚠️ LOS VIDEOS SON DE RELLENO, los del lomo curado en rueda, hasta que
--     Cristian grabe los de cada curso. El TEXTO sí es el definitivo: sale de
--     la receta, que ya está revisada (incluidas las dosis de sal de cura).
--   · Las preguntas para El Charcu (`ask`) son las mismas de la página de la
--     receta (`recipeDoubts`).
--   · `chorizo-santarrosano` ya existía en lista de espera con un guion de 14
--     lecciones sin grabar. Se rehace desde su receta (decisión de Cristian):
--     se borran sus módulos —sin progreso de nadie, estaba cerrado— y su lista
--     de espera se conserva.
--   · Categoría y técnicas: propuesta, igual que en la 0029.
--
-- Por slug y con `on conflict`: aguanta un `db push` sobre una base vacía y
-- volver a aplicarse no duplica nada.
-- ============================================================================
